### ISSUE TITLE
undefined object in `Spat_CV_regular_grid.R`

### ISSUE THREAD

**Issue by jonathom** [AlexandreWadoux/SpatialValidation#1]
Hi @AlexandreWadoux ,
I was trying to reproduce the code here, but I came across an undefined expression in line 112 of `Spat_CV_regular_grid.R`: 
https://github.com/AlexandreWadoux/SpatialValidation/blob/ba3ad39bfa8474a09e8ac4cd82a0161649648794/code/Spat_CV_regular_grid.R#L112
The script doesn't mention how `pp` was made. Could you kindly provide how you constructed `pp` in the original study? 
Thanks!

**Comment by AlexandreWadoux** [comment]
Hello Jonathom, 
The object pp is a polygon including the study area. 
# load polygon of the area
load('./polygon.Rdata')

Alexandre

**Comment by jonathom** [comment]
I missed that line, thank you!
